create_ip -name gtwizard -vendor xilinx.com -library ip -version 3.6 -module_name $name
set ip [get_ips $name]
set config [list \
    CONFIG.identical_protocol_file {Start_from_scratch} \
    CONFIG.gt_val_drp {false} \
    CONFIG.gt0_val_tx_refclk {REFCLK0_Q0} \
    CONFIG.advanced_clocking {false} \
    CONFIG.identical_val_tx_reference_clock {156.250} \
    CONFIG.gt0_val_tx_data_width {32} \
    CONFIG.gt0_val_encoding {None} \
    CONFIG.gt0_val_rx_data_width {32} \
    CONFIG.gt0_val_decoding {None} \
    CONFIG.gt0_val_txbuf_en {false} \
    CONFIG.gt0_val_tx_buffer_bypass_mode {Auto} \
    CONFIG.gt0_val_rxbuf_en {false} \
    CONFIG.gt0_val_rxcomma_deten {false} \
    CONFIG.gt0_val_port_rxpcommaalignen {false} \
    CONFIG.gt0_val_port_rxslide {false} \
    CONFIG.gt0_val_rxprbs_err_loopback {true} \
    CONFIG.identical_val_tx_line_rate {10.3125}\
    CONFIG.identical_val_no_tx {false} \
    CONFIG.identical_val_rx_line_rate {10.3125}\
    CONFIG.identical_val_no_rx {false} \
    CONFIG.gt_val_drp_clock {60} \
    CONFIG.gt0_val {true} \
    CONFIG.gt_val_tx_pll {QPLL} \
    CONFIG.gt_val_rx_pll {QPLL} \
    CONFIG.gt0_val_rx_refclk {REFCLK0_Q0} \
    CONFIG.gt1_val {false} \
    CONFIG.gt1_val_tx_refclk {REFCLK1_Q0} \
    CONFIG.gt1_val_rx_refclk {REFCLK1_Q0} \
    CONFIG.gt2_val {false} \
    CONFIG.gt2_val_tx_refclk {REFCLK1_Q0} \
    CONFIG.gt2_val_rx_refclk {REFCLK1_Q0} \
    CONFIG.gt3_val {false} \
    CONFIG.gt3_val_tx_refclk {REFCLK1_Q0} \
    CONFIG.gt3_val_rx_refclk {REFCLK1_Q0} \
    CONFIG.gt4_val {false} \
    CONFIG.gt4_val_tx_refclk {REFCLK1_Q1} \
    CONFIG.gt4_val_rx_refclk {REFCLK1_Q1} \
    CONFIG.gt5_val {false} \
    CONFIG.gt5_val_tx_refclk {REFCLK1_Q1} \
    CONFIG.gt5_val_rx_refclk {REFCLK1_Q1} \
    CONFIG.gt6_val {false} \
    CONFIG.gt6_val_tx_refclk {REFCLK1_Q1} \
    CONFIG.gt6_val_rx_refclk {REFCLK1_Q1} \
    CONFIG.gt7_val {false} \
    CONFIG.gt7_val_tx_refclk {REFCLK1_Q1} \
    CONFIG.gt7_val_rx_refclk {REFCLK1_Q1} \
    CONFIG.gt8_val {false} \
    CONFIG.gt8_val_tx_refclk {REFCLK1_Q2} \
    CONFIG.gt8_val_rx_refclk {REFCLK1_Q2} \
    CONFIG.gt9_val {false} \
    CONFIG.gt9_val_tx_refclk {REFCLK1_Q2} \
    CONFIG.gt9_val_rx_refclk {REFCLK1_Q2} \
    CONFIG.gt10_val {false} \
    CONFIG.gt10_val_tx_refclk {REFCLK1_Q2} \
    CONFIG.gt10_val_rx_refclk {REFCLK1_Q2} \
    CONFIG.gt11_val {false} \
    CONFIG.gt11_val_tx_refclk {REFCLK1_Q2} \
    CONFIG.gt11_val_rx_refclk {REFCLK1_Q2} \
    CONFIG.gt12_val {false} \
    CONFIG.gt12_val_tx_refclk {REFCLK1_Q3} \
    CONFIG.gt12_val_rx_refclk {REFCLK1_Q3} \
    CONFIG.gt13_val {false} \
    CONFIG.gt13_val_tx_refclk {REFCLK1_Q3} \
    CONFIG.gt13_val_rx_refclk {REFCLK1_Q3} \
    CONFIG.gt14_val {false} \
    CONFIG.gt14_val_tx_refclk {REFCLK1_Q3} \
    CONFIG.gt14_val_rx_refclk {REFCLK1_Q3} \
    CONFIG.gt15_val {false} \
    CONFIG.gt15_val_tx_refclk {REFCLK1_Q3} \
    CONFIG.gt15_val_rx_refclk {REFCLK1_Q3} \
    CONFIG.identical_val_rx_reference_clock {156.250} \
    CONFIG.gt0_val_protocol_file {Start_from_scratch} \
    CONFIG.gt0_val_no_tx {false} \
    CONFIG.gt0_val_no_rx {false} \
    CONFIG.gt0_val_tx_line_rate {10.3125} \
    CONFIG.gt0_val_encoding {None} \
    CONFIG.gt0_val_tx_int_datawidth {32} \
    CONFIG.gt0_val_tx_reference_clock {156.250} \
    CONFIG.gt0_val_rx_line_rate {10.3125} \
    CONFIG.gt0_val_decoding {None} \
    CONFIG.gt0_val_rx_int_datawidth {32} \
    CONFIG.gt0_val_rx_reference_clock {156.250} \
    CONFIG.gt0_val_qpll_refclk_div {1} \
    CONFIG.gt0_val_qpll_fbdiv {66} \
    CONFIG.gt0_val_cpll_rxout_div {1} \
    CONFIG.gt0_val_cpll_txout_div {1} \
    CONFIG.gt0_val_drp {true} \
    CONFIG.gt0_val_drp_clock {100} \
    CONFIG.gt0_val_port_tx8b10bbypass {false} \
    CONFIG.gt0_val_port_txchardispmode {false} \
    CONFIG.gt0_val_port_txchardispval {false} \
    CONFIG.gt0_val_port_rxchariscomma {false} \
    CONFIG.gt0_val_port_rxcharisk {false} \
    CONFIG.gt0_val_txusrclk {TXOUTCLK} \
    CONFIG.gt0_val_txoutclk_source {true} \
    CONFIG.gt0_val_rx_buffer_bypass_mode {Auto} \
    CONFIG.gt0_val_rxusrclk {RXOUTCLK} \
    CONFIG.gt0_val_port_txpcsreset {true} \
    CONFIG.gt0_val_port_txbufstatus {true} \
    CONFIG.gt0_val_port_txrate {false} \
    CONFIG.gt0_val_port_rxpcsreset {true} \
    CONFIG.gt0_val_port_rxbufstatus {true} \
    CONFIG.gt0_val_port_rxbufreset {true} \
    CONFIG.gt0_val_port_rxrate {true} \
    CONFIG.gt0_val_port_txpmareset {true} \
    CONFIG.gt0_val_port_rxpmareset {true} \
    CONFIG.gt0_val_port_rxcdrhold {true} \
    CONFIG.gt0_val_align_mcomma_det {false} \
    CONFIG.gt0_val_align_pcomma_det {false} \
    CONFIG.gt0_val_dec_mcomma_detect {false} \
    CONFIG.gt0_val_dec_pcomma_detect {false} \
    CONFIG.gt0_val_dec_valid_comma_only {false} \
    CONFIG.gt0_val_comma_preset {User_defined} \
    CONFIG.gt0_val_align_pcomma_value {0101111100} \
    CONFIG.gt0_val_align_mcomma_value {1010000011} \
    CONFIG.gt0_val_align_comma_enable {1111111111} \
    CONFIG.gt0_val_align_comma_double {false} \
    CONFIG.gt0_val_align_comma_word {Any_Byte_Boundary} \
    CONFIG.gt0_val_port_rxmcommaalignen {false} \
    CONFIG.gt0_val_port_rxbyteisaligned {false} \
    CONFIG.gt0_val_port_rxbyterealign {false} \
    CONFIG.gt0_val_port_rxcommadet {false} \
    CONFIG.gt0_val_txdiffctrl {true} \
    CONFIG.gt0_val_txpostcursor {true} \
    CONFIG.gt0_val_txprecursor {true} \
    CONFIG.gt0_val_txmaincursor {true} \
    CONFIG.gt0_val_dfe_mode {DFE-Auto} \
    CONFIG.gt0_val_rx_termination_voltage {Programmable} \
    CONFIG.gt0_val_rx_cm_trim {800} \
    CONFIG.gt0_val_port_txpolarity {true} \
    CONFIG.gt0_val_port_txinhibit {true} \
    CONFIG.gt0_val_port_rxpolarity {true} \
    CONFIG.gt0_val_port_rxdfereset {true} \
    CONFIG.gt0_val_port_rxlpmen {true} \
    CONFIG.gt0_val_pcs_pcie_en {false} \
    CONFIG.gt0_val_sata_rx_burst_val {4} \
    CONFIG.gt0_val_sata_e_idle_val {4} \
    CONFIG.gt0_val_pd_trans_time_to_p2 {100} \
    CONFIG.gt0_val_pd_trans_time_from_p2 {60} \
    CONFIG.gt0_val_pd_trans_time_non_p2 {25} \
    CONFIG.gt0_val_port_loopback {true} \
    CONFIG.gt0_val_port_rxstatus {false} \
    CONFIG.gt0_val_port_rxvalid {false} \
    CONFIG.gt0_val_port_cominitdet {false} \
    CONFIG.gt0_val_port_comsasdet {false} \
    CONFIG.gt0_val_port_comwakedet {false} \
    CONFIG.gt0_val_port_txcominit {false} \
    CONFIG.gt0_val_port_txcomsas {false} \
    CONFIG.gt0_val_port_txcomwake {false} \
    CONFIG.gt0_val_port_txcomfinish {false} \
    CONFIG.gt0_val_port_txdetectrx {false} \
    CONFIG.gt0_val_port_txelecidle {false} \
    CONFIG.gt0_val_port_phystatus {false} \
    CONFIG.gt0_val_prbs_detector {true} \
    CONFIG.gt0_val_port_txprbssel {true} \
    CONFIG.gt0_val_port_txprbsforceerr {true} \
    CONFIG.gt0_val_cb {false} \
    CONFIG.gt0_val_cc {false} \
    CONFIG.gt0_val_clk_cor_seq_1_1 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_1_2 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_1_3 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_1_4 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_2_1 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_2_2 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_2_3 {00000000} \
    CONFIG.gt0_val_clk_cor_seq_2_4 {00000000} \
    CONFIG.gt0_val_rxslide_mode {OFF} \
    CONFIG.gt0_val_max_cb_level {7} \
] 
set_property -dict $config $ip
